# Generated by Django 3.0.4 on 2020-04-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(null=True, upload_to='post_photo'),
        ),
    ]
